sonar.organization=mcc-mak
sonar.projectKey=mcc-mak_opencode-sandbox-demo
sonar.projectName=opencode-sandbox-demo

sonar.sources=codebase/site/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/.git/**,.scannerwork/**
sonar.coverage.exclusions=**

sonar.sourceEncoding=UTF-8
